modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="true_end"
version="${modVersion}"
displayName="True End"
displayURL="https://modrinth.com/mod/true_end"
logoFile="icon.png"
authors="Lumynity Studios"
description="But it was all a dream"

[[dependencies.true_end]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minecraftVersion}]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.true_end]]
    modId="terrablender"
    mandatory=true
    versionRange="[${terrablenderVersion},)"
    ordering="NONE"
    side="BOTH"
[[dependencies.true_end]]
    modId="curios"
    mandatory=false
    versionRange="*"
    ordering="NONE"
    side="BOTH"
[[dependencies.true_end]]
    modId="nostalgic_tweaks"
    mandatory=false
    versionRange="*"
    ordering="NONE"
    side="BOTH"
